### PR TITLE
New guidelines

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:bee:

**Comment by cyrille-leclerc** [comment]
:bee:

**Comment by ndeloof** [comment]
are we supposed to :+1: to approve this or just :bee: to confirm we are aware of this change ?

**Comment by recena** [comment]
:bee:

**Comment by aheritier** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees testing

**Comment by ydubreuil** [comment]
:bee:

**Pull request merged**
